### ISSUE TITLE
홈페이지 메인 개선

### ISSUE THREAD

**Issue by Taebu** [Taebu/ezrachurch#30]
화면 아래 슬라이더 생기는 문제 건.

**Comment by Taebu** [comment]
개선전
```css
#main{position:absolute;width:100%}
```

개선후
```css
#main{position:absolute;width:98%;left:1%}
```

- 메인에 h 눌렀을때 메인 글귀 안보이게 토글 되는 방식으로 변경 했습니다. 
- m(mute)키시 다시 원래 소리로 안나오는 부분 수정했습니다.
- up,down key 시 슬라이더가 미동하지 않는 부분 수정했습니다.
- 슬라이더가 아래 생기는 부분 개선 했습니다.
- 음소거 중에는 소리를 제어 할 수 없습니다. 해제 하고 소리를 제어 해야 합니다.
