### ISSUE TITLE
캡쳐 코드 모바일에서 깨져 보일경우 레이아웃

### ISSUE THREAD

**Issue by Taebu** [Taebu/ezrachurch#6]
`.col-xs-##` 는 매우 작은 기기 모바일폰 (<768px)
auto
`.col-sm-##` 작은 기기 태블릿 (≥768px)
750px

`.col-md-##` 중간 기기 데스크탑 (≥992px)
970px

`.col-lg-##` 는 "큰 기기 데스크탑 (≥1200px)"
1170px

```html
<div class="row">
<div class="col-xs-12 col-sm-4 col-lg-2"></div>
<div class="col-xs-6 col-sm-4 col-lg-2"></div>
<div class="col-xs-6 col-sm-4 col-lg-2 "></div>
<div class="col-xs-12 col-sm-112 col-lg-6 "></div>
</div>
```

잘못된 레이아웃으로 모바일 레이아웃 구성시 레이아웃이 눌리지 않는 미디어 쿼리 문제
```html
<div class="col-sm-12 col-md-12 inset-sm">
<h1>개인정보</h1>
...
</div>
<div class="col-sm-12 col-md-12 inset-sm">
<h1>기타정보</h1>
...
</div>
```

아래와 같이 고치면 된다.

```html
<div class="col-xs-12">
<h1>개인정보</h1>
...
</div>
<div class="col-xs-12">
<h1>기타정보</h1>
...
</div>
```

주소 부분 버튼
`.col-xs-12 col-lg-2`

캡쳐 버튼 마지막 버튼 버그
```html
<div class="col-sm-12">
to-->
<div class="col-xs-12">
  <div class="form-group"><input type="text" name="captcha_key" id="captcha_key" required="" class="form-control round-small captcha_box required">
  </div>
</div>
```

**Comment by Taebu** [comment]
http://anp.cashq.co.kr:82/theme/modificate/css/style.css
```css
// line 3949
label {
  display: inline-block;
  max-width: 100%;
  margin-bottom: 5px;
  font-weight: bold;
  color: #14a5eb;
  letter-spacing: 0.06em;
}

//line 4156
.form-control {
  display: block;
  width: 100%;
  height: 50px;
  padding: 11.5px 25px;
  font-size: 14px;
  line-height: 1.78571;
  color: #262032;
  background-color: #f2f2f2;
  background-image: none;
  border: 1px solid #f2f2f2;
  border-radius: 30px;
  -webkit-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
  -o-transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
  transition: border-color ease-in-out 0.15s, box-shadow ease-in-out 0.15s;
}

```
